env:
  global:
    CC_TEST_REPORTER_ID=fb8d7bba7555d7b2efde0e78d717202f90badb1e22eaae2c628bbd55d5c84b38

language: node_js

node_js:
  - stable

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm run test

after_script:
  - ./cc-test-reporter after-build -t lcov --exit-code $TRAVIS_TEST_RESULT