env:
  global:
    CC_TEST_REPORTER_ID=1c3ada6bf34de9f12e849afcd63679b45e35b2198041843f734c7e07021d4e9f

language: node_js

node_js:
  - lts/*

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm run test

after_script:
  - ./cc-test-reporter after-build -t lcov --exit-code $TRAVIS_TEST_RESULT